# what is abstraction?
# The process of handling complexity by hiding unnecessary 
#information from user is called abstraction...
# hiding internal functionality is also called abstraction......
# For example......
# All of you know about ATM Machine....
# if we went to atm select withdraw money by selecting some options, if we select an option we dont know about 
#the internal process what happened , but we are withdraw money...