# In multilevel inheritance we will deal with atleast 3 classes...
# class is derived from a class and which is already derived from another class.....

#Example:
#class A ------> class B(A) ------> class C(B)